'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import type { GameModule } from './registry';
import { Avatar3D } from '@/components/Avatar3D';
import { awardScores, dispatchLive, getSessionUid, setLive, subscribeLive, subscribeRoom } from '@/lib/room-store';
import type { Action, LiveState, RoomMeta } from '@/lib/types';
import { flashBuzzer } from '@/lib/anime';

const QUESTIONS = [
  { q: 'Which film features the line "I am your father"?', choices: ['Star Wars: A New Hope', 'The Empire Strikes Back', 'Return of the Jedi', 'Rogue One'], a: 1, cat: 'Plot & Story' },
  { q: 'Who directed Inception (2010)?', choices: ['Steven Spielberg', 'Ridley Scott', 'Christopher Nolan', 'James Cameron'], a: 2, cat: 'Directors & Cast' },
  { q: 'A hobbit destroys a powerful ring in a volcano. Name the film.', choices: ['The Hobbit', 'Lord of the Rings: Fellowship', 'Lord of the Rings: Return of the King', 'Excalibur'], a: 2, cat: 'Guess the Movie' },
  { q: 'Which actor played Tony Stark / Iron Man across the MCU?', choices: ['Chris Evans', 'Robert Downey Jr.', 'Chris Pratt', 'Mark Ruffalo'], a: 1, cat: 'Directors & Cast' },
  { q: 'In which film does a clownfish cross the ocean to find his son?', choices: ['Shark Tale', 'Finding Nemo', 'Finding Dory', 'The Little Mermaid'], a: 1, cat: 'Guess the Movie' },
  { q: 'Who directed Pulp Fiction (1994)?', choices: ['Martin Scorsese', 'Quentin Tarantino', 'David Fincher', 'Coen Brothers'], a: 1, cat: 'Directors & Cast' },
  { q: 'A man wakes up reliving the same day over and over in a small town. Name the film.', choices: ['Edge of Tomorrow', 'Source Code', 'Groundhog Day', '12 Monkeys'], a: 2, cat: 'Guess the Movie' },
  { q: 'What year did Titanic (James Cameron) release?', choices: ['1994', '1995', '1997', '1999'], a: 2, cat: 'Plot & Story' },
  { q: "In The Dark Knight, what is the Joker's actor's name?", choices: ['Jack Nicholson', 'Joaquin Phoenix', 'Heath Ledger', 'Jared Leto'], a: 2, cat: 'Directors & Cast' },
  { q: 'A janitor at MIT solves a nearly impossible math problem on a chalkboard. Name the film.', choices: ['A Beautiful Mind', 'Good Will Hunting', 'Pi', 'Proof'], a: 1, cat: 'Guess the Movie' },
  { q: "Which film ends with the reveal that the narrator's imaginary friend is Tyler Durden?", choices: ['American Psycho', 'Shutter Island', 'Fight Club', 'Black Swan'], a: 2, cat: 'Plot & Story' },
  { q: 'Who played Hermione Granger in the Harry Potter series?', choices: ['Emma Watson', 'Emma Stone', 'Keira Knightley', 'Natalie Portman'], a: 0, cat: 'Directors & Cast' },
  { q: 'A young lion cub flees after his father is murdered by his uncle. Name the film.', choices: ['Bambi', 'The Jungle Book', 'The Lion King', 'Brother Bear'], a: 2, cat: 'Guess the Movie' },
  { q: 'In Avengers: Infinity War, which stone does Thanos get from Vision?', choices: ['Time Stone', 'Space Stone', 'Mind Stone', 'Soul Stone'], a: 2, cat: 'Plot & Story' },
  { q: 'Which director made Schindler\'s List, Saving Private Ryan, and Jurassic Park?', choices: ['James Cameron', 'Steven Spielberg', 'Peter Jackson', 'Ron Howard'], a: 1, cat: 'Directors & Cast' },
];
interface MVState extends LiveState { phase: 'waiting' | 'question' | 'buzzed' | 'reveal' | 'done'; qIndex: number; buzzedUid: string | null; buzzOrder: string[]; correctUid: string | null; picked: number | null; }
function init(): MVState { return { phase: 'waiting', qIndex: 0, buzzedUid: null, buzzOrder: [], correctUid: null, picked: null }; }
function applyAction(state: LiveState, action: Action): LiveState {
  const s = state as MVState;
  switch (action.type) {
    case 'ask': return { ...s, phase: 'question', qIndex: action.payload.qIndex, buzzedUid: null, buzzOrder: [], correctUid: null, picked: null };
    case 'buzz': if (s.phase !== 'question' || (s.buzzOrder || []).includes(action.uid)) return s; return { ...s, phase: 'buzzed', buzzedUid: action.uid, buzzOrder: [...(s.buzzOrder || []), action.uid] };
    case 'answer': { const correct = action.payload.choice === QUESTIONS[s.qIndex]!.a; return correct ? { ...s, phase: 'reveal', correctUid: action.uid, picked: action.payload.choice } : { ...s, phase: 'question', buzzedUid: null, picked: action.payload.choice }; }
    case 'next': { const qIndex = s.qIndex + 1; return qIndex >= QUESTIONS.length ? { ...s, phase: 'done' } : { ...s, phase: 'question', qIndex, buzzedUid: null, buzzOrder: [], correctUid: null, picked: null }; }
    case 'end': return { ...s, phase: 'done' };
    default: return s;
  }
}
function CinemaScene({ players, buzzedUid, correctUid }: { players: RoomMeta['players']; buzzedUid: string | null; correctUid: string | null }) {
  const spotRef = useRef<any>(null); const reelRef = useRef<any>(null);
  useFrame(({ clock }) => { const t = clock.getElapsedTime(); if (spotRef.current) spotRef.current.intensity = buzzedUid ? 35 + Math.sin(t * 9) * 12 : 14; if (reelRef.current) reelRef.current.rotation.z = t * 0.6; });
  return <group><mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.01, 0]}><planeGeometry args={[26, 16]} /><meshStandardMaterial color="#0a0a1c" roughness={0.9} /></mesh><mesh position={[0, 2.2, -5.5]}><planeGeometry args={[9, 4]} /><meshStandardMaterial color="#e8e0d0" emissive="#fffbe8" emissiveIntensity={buzzedUid ? 0.6 : 0.2} roughness={0.7} /></mesh><group ref={reelRef} position={[6, 3.5, -3]}><mesh><torusGeometry args={[0.55, 0.1, 8, 24]} /><meshStandardMaterial color="#888" metalness={0.8} roughness={0.3} /></mesh><mesh><circleGeometry args={[0.38, 24]} /><meshStandardMaterial color="#222" /></mesh></group><pointLight ref={spotRef} position={[0, 8, 2]} intensity={14} distance={22} color={correctUid ? '#34D399' : buzzedUid ? '#FF3D81' : '#fffbe8'} />{[-3, -1, 1, 3].map((x) => <mesh key={x} position={[x * 1.5, 0.35, 2.5]}><boxGeometry args={[0.9, 0.7, 0.5]} /><meshStandardMaterial color="#1e1e3c" roughness={0.8} /></mesh>)}{players.map((p, i) => { const x = (i - (players.length - 1) / 2) * 2.1; const hot = p.uid === (correctUid ?? buzzedUid); return <group key={p.uid} position={[x, 0, 0.5]}><mesh position={[0, 0.3, 0]}><cylinderGeometry args={[0.5, 0.6, 0.6, 16]} /><meshStandardMaterial color={correctUid === p.uid ? '#34D399' : hot ? '#FF3D81' : '#1e1e3c'} emissive={hot ? (correctUid === p.uid ? '#34D399' : '#FF3D81') : '#000'} emissiveIntensity={hot ? 0.9 : 0} /></mesh><Avatar3D color={p.avatarColor} name={p.name} position={[0, 0.6, 0]} highlight={hot} /></group>; })}</group>;
}
function GameScene({ roomCode }: { roomCode: string }) {
  const uid = useMemo(() => getSessionUid(), []); const [live, setL] = useState<MVState | null>(null); const [room, setRoom] = useState<RoomMeta | null>(null);
  useEffect(() => subscribeLive(roomCode, (s) => setL((s as MVState) ?? null)), [roomCode]); useEffect(() => subscribeRoom(roomCode, setRoom), [roomCode]);
  const isHost = room?.hostId === uid; const q = live ? QUESTIONS[live.qIndex] : null; const myTurn = live?.buzzedUid === uid; const lockedOut = !!live && live.phase === 'question' && (live.buzzOrder || []).includes(uid) && (live.buzzOrder || [])[0] !== uid;
  const act = (type: string, payload: any = {}) => dispatchLive(roomCode, { type, uid, payload }, applyAction, init);
  const buzz = () => { act('buzz'); flashBuzzer('#buzz-btn', '#FF3D81'); }; const answer = (choice: number) => { const correct = choice === QUESTIONS[live!.qIndex]!.a; if (correct) { void awardScores(roomCode, { [uid]: 100 }); flashBuzzer('#mv-quiz-card', '#34D399'); } act('answer', { choice }); };
  return <div className="flex h-full flex-col gap-2 lg:flex-row"><div className="relative min-h-[300px] flex-1 overflow-hidden rounded-2xl border border-white/10"><Canvas camera={{ position: [0, 5, 10], fov: 50 }} dpr={[1, 1.75]}><color attach="background" args={['#080818']} /><ambientLight intensity={0.35} /><directionalLight position={[4, 7, 3]} intensity={0.6} />{room && <CinemaScene players={room.players} buzzedUid={live?.buzzedUid ?? null} correctUid={live?.correctUid ?? null} />}</Canvas>{q && <div className="absolute bottom-3 left-3 right-3 arcade-card px-3 py-1.5 text-center"><span className="text-xs font-bold uppercase tracking-widest text-[#FFC53D]">{q.cat}</span><span className="mx-2 text-white/30">·</span><span className="text-xs text-white/60">Q{live!.qIndex + 1} / {QUESTIONS.length}</span></div>}</div><div className="flex w-full flex-col gap-2 lg:w-96">
    {(!live || live.phase === 'waiting') && <div className="arcade-card p-4"><div className="font-display text-lg font-extrabold">🎬 Movie Trivia</div><p className="mt-1 text-sm text-white/70">15 questions · Plot, Cast, Guess-the-Movie. Buzz in first, answer correctly for +100.</p>{isHost ? <button onClick={() => act('ask', { qIndex: 0 })} className="btn-neon mt-3 w-full rounded-xl px-3 py-2 text-sm font-bold">🎬 Start Trivia</button> : <p className="mt-2 text-sm text-white/60">Waiting for host…</p>}</div>}
    {live && (live.phase === 'question' || live.phase === 'buzzed') && q && <div id="mv-quiz-card" className="arcade-card p-4"><div className="mb-1 text-xs font-bold uppercase tracking-widest text-[#FFC53D]">{q.cat} · Q{live.qIndex + 1}</div><div className="font-display text-lg font-extrabold leading-snug">{q.q}</div>{live.phase === 'question' && !lockedOut && <button id="buzz-btn" onClick={buzz} className="btn-neon mt-3 w-full rounded-xl px-3 py-3 font-display text-xl font-extrabold">🎬 BUZZ IN</button>}{lockedOut && <p className="mt-2 text-sm text-white/60">You answered wrong — locked out this question.</p>}{live.phase === 'buzzed' && <p className="mt-2 text-sm font-bold text-[#FF3D81]">{myTurn ? '🎯 You have the mic — pick your answer!' : `${room?.players.find((p) => p.uid === live.buzzedUid)?.name} is answering…`}</p>}<div className="mt-2 grid gap-1.5">{q.choices.map((c, i) => <button key={i} disabled={!myTurn} onClick={() => answer(i)} className={`rounded-xl px-3 py-2 text-left text-sm font-semibold ${myTurn ? 'bg-white/10 hover:bg-[#FF3D81]/40' : 'bg-white/5 text-white/60'}`}>{String.fromCharCode(65 + i)}. {c}</button>)}</div>{isHost && <button onClick={() => act('next')} className="mt-2 w-full rounded-xl bg-white/10 px-3 py-2 text-xs font-bold">Skip →</button>}</div>}
    {live?.phase === 'reveal' && q && <div className="arcade-card border-[#34D399]/50 p-4 text-center"><div className="font-display text-xl font-extrabold text-[#34D399]">✅ {room?.players.find((p) => p.uid === live.correctUid)?.name} scores +100!</div><p className="mt-1 text-sm text-white/70">Answer: {q.choices[q.a]}</p>{isHost && <div className="mt-2 flex gap-1"><button onClick={() => act('next')} className="btn-neon flex-1 rounded-xl px-3 py-2 text-sm font-bold">Next question</button><button onClick={() => act('end')} className="flex-1 rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">Finish</button></div>}</div>}
    {live?.phase === 'done' && <div className="arcade-card p-4 text-center"><div className="font-display text-xl font-extrabold">🎬 That's a wrap! 🎉</div>{isHost && <button onClick={() => void setLive(roomCode, null)} className="btn-neon mt-2 rounded-xl px-4 py-2 text-sm font-bold">Back to lobby scoring</button>}</div>}
  </div></div>;
}
function Preview() { const reelRef = useRef<any>(null); const screenRef = useRef<any>(null); useFrame(({ clock }) => { const t = clock.getElapsedTime(); if (reelRef.current) reelRef.current.rotation.z = t * 0.8; if (screenRef.current) screenRef.current.material.emissiveIntensity = 0.3 + Math.sin(t * 2) * 0.2; }); return <group><mesh ref={screenRef} position={[0, 0.3, -0.3]}><planeGeometry args={[1.8, 0.9]} /><meshStandardMaterial color="#e8e0d0" emissive="#fffbe8" emissiveIntensity={0.3} /></mesh><group ref={reelRef} position={[0.9, 0.8, 0]}><mesh><torusGeometry args={[0.28, 0.06, 6, 16]} /><meshStandardMaterial color="#888" metalness={0.8} /></mesh></group></group>; }
export const MovieTrivia: GameModule = { id: 'movietrivia', displayName: 'Movie Trivia', tagline: 'Lights, camera, buzz in!', minPlayers: 2, maxPlayers: 8, accent: '#FFC53D', LobbyPreviewScene: Preview, GameScene, applyAction, initState: () => init() };
